name: Deploy to Render on Release Branch

on:
  push:
    branches:
      - 'release/sfmanagement.V*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
