name: Deploy to Render on Release Branch

on:
  push:
    branches:
      - 'release/sfmanagement.V*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar SDK de .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Compilar proyecto
        run: dotnet build --no-restore --configuration Release

      # Se eliminó la instalación de Playwright para ahorrar tiempo y recursos

      - name: Ejecutar Tests Unitarios e Integración
        env:
          TESTCONTAINERS_RYUK_DISABLED: "true"
        run: |
          dotnet test tests/SFManagement.UnitTests/SFManagement.UnitTests.csproj --no-build --verbosity normal --configuration Release
          dotnet test tests/SFManagement.IntegrationTests/SFManagement.IntegrationTests.csproj --no-build --verbosity normal --configuration Release --maxcpucount:1

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"